### ISSUE TITLE
Is it possible not to scroll to latest selected item in the list on open dropdown?

### ISSUE THREAD

**Issue by Denisiums** [ng-select/ng-select#1140]
When you have preselected items for multiselect, 1st time the list won't be scrolled (stays on top). If you open it next time, it'll be scrolled to the latest selected item.
Do we have any option to start from the 'top' of the list all times for multiselect (even if something was selected before)?

P. S. may it be a bug?

**Comment by Denisiums** [comment]
Ok, here's really ugly workaround.
`onOpen() {
    setTimeout(() => {
      const scrollContainer = document.querySelector('.ng-dropdown-panel-items');
      if (scrollContainer) {
        scrollContainer.scrollTop = 0;
      }
    }, 0);
  }
`

**Comment by varnastadeus** [comment]
> When you have preselected items for multiselect, 1st time the list won't be scrolled (stays on top). If you open it next time, it'll be scrolled to the latest selected item.

> 
> P. S. may it be a bug?

there was a bug and it should be fixed in the latest version

**Comment by shayb-datumate** [comment]
I also need to have the option not to scroll to the selected element when the popup is opened.
Is it possible without doing that ugly workaround?

**Comment by creffect** [comment]
Is seems to be intended behaviour, i checked the code and found in ng-ddropdown-panel.component.ts follwoing code (line 115 following):

![image](https://user-images.githubusercontent.com/8288442/108867616-aaec9200-75f5-11eb-99c4-aae33f4e4f86.png)

Commenting out the top part solved the issue. Of course, a clean solution would be an option for it....

**Comment by creffect** [comment]
`private get _startOffset() {
    // EDIT Don't scroll to last Item, if >= 2 are selected
    const selectedItems = this.items.filter(item => item.selected)
    if (selectedItems.length >= 2) {
      this.markedItem = selectedItems[0]
    }
    // END EDIT
    if (this.markedItem) {
      const { itemHeight, panelHeight } = this._panelService.dimensions;
      const offset = this.markedItem.index * itemHeight;
      return panelHeight > offset ? 0 : offset;
    }
    return 0;
  }`

**Comment by souravsaraf123** [comment]
issue mentioned by @lschuft still exists and we are also troubled by this ...

Can you please reopen the issue @varnastadeus  ?

**Comment by cmgchess** [comment]
Also have the same issue.  
https://github.com/ng-select/ng-select/discussions/2363
