### ISSUE TITLE
ng-select Template parse errors: Can't bind to 'items' since it isn't a known property of 'ng-select

### ISSUE THREAD

**Issue by almgwary** [ng-select/ng-select#602]
### behaviour
ng-select Template parse errors: Can't bind to 'items' since it isn't a known property of 'ng-select
### More Info
ng-select version: [^2.1.3]

**Comment by anjmao** [comment]
Hi @almgwary,
Have you included NgSelectModule in your AppModule or over ChildModule?

**Comment by ChrisB92** [comment]
I've just had this error as well. I've included NgSelectModule in AppModule.

**Comment by almgwary** [comment]
yes i included it in the shared module,

**Comment by almgwary** [comment]
Solved by importing NgSelectModule  in the component module itself. 

But why it is not working in the SharedModule.
SharedModule  is being imported everywhere and with forRoot in the root AppModule

**Comment by varnastadeus** [comment]
probably you forgot to re-export it or something

**Comment by crissty** [comment]
Hi, I getthe same error.

I have imported FormsModule and NgSelectModule in the AppModule, but when I navigate to the componenet the error:  "Can't bind to 'items' since it isn't a known property of 'ng-select" is released.

Does anyone know why it happen?
Thanks

**Comment by tiagomsmagalhaes** [comment]
I'm facing the same error I'm modulating an app with a appmodule with othermodules that share a sharedmodule with components.

**Comment by pavangayakwad** [comment]
Those who are still getting this error, I am able to solve it by importing `NgSelectModule` inside `app.module.ts` and AS WELL in the module where my component is using it.
