### ISSUE TITLE
Dropdown position is incorrect when ng-select is placed in a scrollable container

### ISSUE THREAD

**Issue by earshinov** [ng-select/ng-select#799]
**Bug Description**

In https://github.com/ng-select/ng-select/issues/237 and https://github.com/ng-select/ng-select/pull/238 ng-select learned to display its dropdown above the select in case there is no enough room below. It does not seem to work when ng-select is placed in a scrollable container.

**To Reproduce**
1. Visit the demo page https://stackblitz.com/edit/angular-rxjygd.
2. Scroll the scrollable element to the end to reveal the test ng-select.
3. Expand ng-select by pressing the arrow button.
4. The dropdown appears under the select and is not fully visible to the user until he/she scrolls the scrollable element further down.

![ng-select incorrect dropdown position demo](https://user-images.githubusercontent.com/52021/45235848-d32b8d80-b2e2-11e8-9510-e6a3cca40903.png)

**Expected behavior**
In the reproduction scenario, the dropdown should be placed above the select so that it is fully visible to the user.

I believe that generally `NgDropdownPanelComponent._calculateCurrentPosition` method should consider ng-select's position relative to its nearest parent with `overflowY != 'visible'`. If there is no such parent, the method should rely on `body` / `window` as it does unconditionally now.

**Environment:**
(does not really matter)
 - OS: Windows 10 x64
 - Browser: Google Chrome 68.0.3440.106 (Official Build) (64-bit)

**Comment by IvanLy-in6k** [comment]
+1

**Comment by umeshdk** [comment]
+1

**Comment by volodymyro-in6k** [comment]
+1

**Comment by ccd2008** [comment]
+1

**Comment by MrBra1nwash** [comment]
+1

**Comment by heisaman** [comment]
+1

**Comment by Troyd-Destin** [comment]
+1    My dropdowns are unusable with the virtual scroll feature

**Comment by jmemmons** [comment]
Can I go ahead and fix this? The Contributing section in the README states that `Contributions are welcome. You can start by looking at issues with label Help wanted`. This does not have such a label, in fact, none of the opened issues have that label. Just wondering if I can contribute or not

**Comment by varnastadeus** [comment]
ofcourse you can

**Comment by info-lvsys** [comment]
So, how do you fix this one? This issue appears also when the drop down is in a bootstrap modal dialog box. For some reason it causes the modal to show a scrollbar and the dropdown items are partially hidden, see screenshot:

![image](https://user-images.githubusercontent.com/7323260/52838085-41505980-30a6-11e9-9c66-1abbab4346d8.png)

**Comment by info-lvsys** [comment]
This happens also within a bootstrap 4 modal dialog box. Its weird (See screenshot). how do you fix it?

![image](https://user-images.githubusercontent.com/7323260/52838204-b754c080-30a6-11e9-83cc-b9cddf2a7097.png)

**Comment by varnastadeus** [comment]
@info-lvsys I am not sure what fix you are expecting. You have container with overflow and content inside that container will stay in the same block formatting context. 
Imagine you have button which adds table inside your modal with overflow, will you expect it to appear on top of modal fully visible? Obviously not, it will just expand your overflowing content as in your example above.

Of course this not perfect situation thats why we have addressed this with `appendTo="body"` which will render dropdown inside `body` allowing it to appear on top any element fully visible. Cheers

**Comment by info-lvsys** [comment]
@varnastadeus awesome. appendTo="body" fixed it :) 

yeah, we always want the dropdown to appear above everything in our UI's (dialog, etc), regardless of where the select is located. This works perfectly now.

Thank you :)

**Comment by jcubic** [comment]
I think this can be closed or docs/FAQ can be updated, `appendTo="body"` is the only solution. You need to have dropdown outside of scrollable container. This is how CSS works.

**Comment by earshinov** [comment]
Sorry, I must have accidentally removed the original demo page because of its non-descriptive name.
Restored it: https://stackblitz.com/edit/angular-ng-select-dropdown-position

**Comment by earshinov** [comment]
@jcubic , appendTo="body" does not solve the problem from the description. You can try it yourself on the demo page.

People who have a simple overflow:hidden issue (which is solved by appendTo="body") come across this issue, see some similarity and report their problems here. But the problem addressed in this issue is actually different.

**Comment by earshinov** [comment]
For the record, here is what happens with `appendTo="body"`:

![appendTo body](https://user-images.githubusercontent.com/52021/55279851-a6969c00-532e-11e9-95c5-3125050e6a6a.png)

**Comment by kkseven07** [comment]
I'm a newbie in Angular, but I'm familiar with this problem in React. Does Angular have any feature like Portaling in React? This may help

**Comment by varnastadeus** [comment]
I think `appendTo="body"` is valid solution and I am not sure if something else needs to be done here. Don't forget to set
```css
body {
    position: relative;
}
```
with appendTo body as mentioned in docs

**Comment by earshinov** [comment]
@varnastadeus , Just to clarify, did you care to read my comment right above? https://github.com/ng-select/ng-select/issues/799#issuecomment-478270357

**Comment by varnastadeus** [comment]
did you care to read mine?

**Comment by varnastadeus** [comment]
I did and I understand that you have a slightly different use case, but since `appendTo="body"` fixes both issues it is a valid solution. 

Also if your parent container would have a smaller height (eg.: 200px) dropdown wouldn't fit in both directions. In that case, the only option would be `appendTo="body"`

**Comment by MonstraG** [comment]
Came across issue pointed out by @earshinov, already using `appendTo="body"`, and `body { position: relative; }`

![image](https://user-images.githubusercontent.com/17963791/63000936-d4b6eb80-be8b-11e9-9908-f9f54a55b5b2.png)

**Comment by stevebrowndotco** [comment]
Hello, I can confirm that this bug is present after updating ng-select.

The *issue* is that the inline styles of ng-select are not updating correctly on the window resize event. Try dragging the browser window and you'll see.

My solution was to pin my version in my package json, affectively downgrading. I'm using `2.13.1` where it works.

**Comment by stevebrowndotco** [comment]
Workaround for now:

Fire this function on the blur and click events:

```typescript
  forceResizeWindow() {
      window.dispatchEvent(new Event('resize'));
  }
```

Avoid a flash in the change of position:

```css
::ng-deep ng-dropdown-panel {
    transition: opacity 0.1s linear;
}
```

**Comment by varnastadeus** [comment]
> I think `appendTo="body"` is valid solution and I am not sure if something else needs to be done here. Don't forget to set
> 
> ```css
> // styles.css
> body {
>     position: relative;
> }
> ```
> 
> with appendTo body as mentioned in docs

I am closing this issue since most of the comments are not related to the original issue and should be addressed elsewhere. Also, for now`appendTo="body"` is considered as the right solution until better implementation of panel positioning is found.
